export const REQUEST_FETCH_CUSTOMERS = "REQUEST_FETCH_CUSTOMER";
export const REQUEST_FETCH_CUSTOMERS_PENDING = "REQUEST_FETCH_CUSTOMER_PENDING";
export const REQUEST_FETCH_CUSTOMERS_SUCCESS = "REQUEST_FETCH_CUSTOMER_SUCCESS";
export const REQUEST_FETCH_CUSTOMERS_FAILED = "REQUEST_FETCH_CUSTOMER_FAILED";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMER";