export const REQUEST_FETCH_CUSTOMER_ORDERS = "REQUEST_FETCH_CUSTOMER_ORDERS";
export const REQUEST_FETCH_CUSTOMER_ORDERS_PENDING = "REQUEST_FETCH_CUSTOMER_ORDERS_PENDING";
export const REQUEST_FETCH_CUSTOMER_ORDERS_SUCCESS = "REQUEST_FETCH_CUSTOMER_ORDERS_SUCCESS";
export const REQUEST_FETCH_CUSTOMER_ORDERS_FAILED = "REQUEST_FETCH_CUSTOMER_ORDERS_FAILED";
export const FETCH_CUSTOMER_ORDERS = "FETCH_CUSTOMER_ORDERS";