export const REQUEST_SEARCH_PRODUCTS = "REQUEST_SEARCH_PRODUCTS";
export const REQUEST_SEARCH_PRODUCTS_PENDING = "REQUEST_SEARCH_PRODUCTS_PENDING";
export const REQUEST_SEARCH_PRODUCTS_SUCCESS = "REQUEST_SEARCH_PRODUCTS_SUCCESS";
export const REQUEST_SEARCH_PRODUCTS_FAILED = "REQUEST_SEARCH_PRODUCTS_FAILED";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";

export const REQUEST_FETCH_CATEGORIES = "REQUEST_FETCH_CATEGORIES";
export const REQUEST_FETCH_CATEGORIES_PENDING = "REQUEST_FETCH_CATEGORIES_PENDING";
export const REQUEST_FETCH_CATEGORIES_SUCCESS = "REQUEST_FETCH_CATEGORIES_SUCCESS";
export const REQUEST_FETCH_CATEGORIES_FAILED = "REQUEST_FETCH_CATEGORIES_FAILED";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";